name: Documentation Issue
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Setup Guide
        - Deployment Guide
        - Code Comments
        - Architecture Docs
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe what's missing or incorrect
      placeholder: The documentation for X is unclear because...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: File path or URL of the documentation
      placeholder: e.g., README.md, apps/api/src/auth/README.md

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve it?
      placeholder: I suggest adding/changing...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
