name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this affect?
      options:
        - Frontend (Next.js)
        - Backend (NestJS API)
        - Database Schema
        - Authentication
        - Payment Integration
        - Page Builder
        - Shopping Cart
        - Order Management
        - Analytics
        - API/Developer Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (required for production use)
        - High (very important)
        - Medium (nice to have)
        - Low (optional enhancement)
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - Store Owners
        - Developers
        - End Customers
        - Administrators
        - All Users
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add mockups, screenshots, or examples if applicable

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information
