'use client';

import {
  Zap,
  Droplet,
  Sun,
  Shield,
  ShieldCheck,
  Truck,
  Headphones,
  Star,
  Heart,
  Check,
  CheckCircle,
  Clock,
  Package,
  Lock,
  Eye,
  ThumbsUp,
  Award,
  Gift,
  Target,
  TrendingUp,
  BarChart,
  Users,
  Globe,
  Smartphone,
  Monitor,
  Wifi,
  Cloud,
  Database,
  Settings,
  Search,
  Bell,
  Mail,
  MessageCircle,
  Phone,
  MapPin,
  Calendar,
  CreditCard,
  DollarSign,
  Percent,
  Tag,
  ShoppingCart,
  ShoppingBag,
  Bookmark,
  Flag,
  AlertCircle,
  Info,
  HelpCircle,
  RefreshCw,
  RotateCcw,
  ArrowRight,
  ArrowUp,
  ChevronRight,
  Play,
  Pause,
  Volume2,
  Camera,
  Image,
  FileText,
  Layers,
  Layout,
  Grid,
  List,
  PenTool,
  Palette,
  Sparkles,
  Flame,
  Leaf,
  Coffee,
  Smile,
  Frown,
  Meh,
  Activity,
  Rocket,
  Lightbulb,
  BatteryCharging,
  Compass,
  Crown,
  Diamond,
  Fingerprint,
  Gauge,
  Gem,
  HandMetal,
  Infinity,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  zap: Zap,
  droplet: Droplet,
  sun: Sun,
  shield: Shield,
  'shield-check': ShieldCheck,
  truck: Truck,
  headphones: Headphones,
  star: Star,
  heart: Heart,
  check: Check,
  'check-circle': CheckCircle,
  clock: Clock,
  package: Package,
  lock: Lock,
  eye: Eye,
  'thumbs-up': ThumbsUp,
  award: Award,
  gift: Gift,
  target: Target,
  'trending-up': TrendingUp,
  'bar-chart': BarChart,
  users: Users,
  globe: Globe,
  smartphone: Smartphone,
  monitor: Monitor,
  wifi: Wifi,
  cloud: Cloud,
  database: Database,
  settings: Settings,
  search: Search,
  bell: Bell,
  mail: Mail,
  'message-circle': MessageCircle,
  phone: Phone,
  'map-pin': MapPin,
  calendar: Calendar,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  percent: Percent,
  tag: Tag,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  bookmark: Bookmark,
  flag: Flag,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'chevron-right': ChevronRight,
  play: Play,
  pause: Pause,
  volume: Volume2,
  camera: Camera,
  image: Image,
  'file-text': FileText,
  layers: Layers,
  layout: Layout,
  grid: Grid,
  list: List,
  'pen-tool': PenTool,
  palette: Palette,
  sparkles: Sparkles,
  flame: Flame,
  leaf: Leaf,
  coffee: Coffee,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  activity: Activity,
  rocket: Rocket,
  lightbulb: Lightbulb,
  'battery-charging': BatteryCharging,
  compass: Compass,
  crown: Crown,
  diamond: Diamond,
  fingerprint: Fingerprint,
  gauge: Gauge,
  gem: Gem,
  'hand-metal': HandMetal,
  infinity: Infinity,
};

/**
 * Resolves a string icon name to its lucide-react component.
 * Falls back to CheckCircle if the icon name is not found.
 */
export function getIcon(name: string): LucideIcon {
  if (!name) return CheckCircle;
  const normalized = name.toLowerCase().trim();
  return iconMap[normalized] ?? CheckCircle;
}

export { iconMap };
